In [1]:
import numpy as np

# Indexing over array

In [2]:
a = np.array([[1, 2, 1, 7], [4, 5, 6, 9], [5, 7, 8, 1]])
a

array([[1, 2, 1, 7],
       [4, 5, 6, 9],
       [5, 7, 8, 1]])

In [3]:
# access the element using index
# get 1st row
a[0]

array([1, 2, 1, 7])

In [4]:
# get 3 rd row
a[2]

array([5, 7, 8, 1])

In [5]:
# i want to last row
a[-1]

array([5, 7, 8, 1])

In [6]:
# we can change the value of array using index
a[0][1]

2

In [7]:
# we pass the value through indxing it will inplace of array.
a[0][1] = 10
a

array([[ 1, 10,  1,  7],
       [ 4,  5,  6,  9],
       [ 5,  7,  8,  1]])

In [8]:
# same as above 
a[1,0] = 14
a

array([[ 1, 10,  1,  7],
       [14,  5,  6,  9],
       [ 5,  7,  8,  1]])

In [9]:
# by default access the row 
a[1]

array([14,  5,  6,  9])

# Slicing

In [10]:
#using indexing we can access one row at a time
# but now i want to access multiple rows
a[:]

array([[ 1, 10,  1,  7],
       [14,  5,  6,  9],
       [ 5,  7,  8,  1]])

In [11]:
# i want fetch last two rows
a[1:]

array([[14,  5,  6,  9],
       [ 5,  7,  8,  1]])

In [12]:
# reverse the row
a[::-1]

array([[ 5,  7,  8,  1],
       [14,  5,  6,  9],
       [ 1, 10,  1,  7]])

# column access

In [13]:
# all row and columns
a[:,:]

array([[ 1, 10,  1,  7],
       [14,  5,  6,  9],
       [ 5,  7,  8,  1]])

In [14]:
# i want to access the column
# it will get the 2 column presnt in 1st index
a[:,1]

array([10,  5,  7])

In [15]:
# fetch multiple columns
a[:,1:]

array([[10,  1,  7],
       [ 5,  6,  9],
       [ 7,  8,  1]])

In [16]:
# i want to fetch selected columns
# we put the sequnce of columns index that sequnce it will follow.
a[:, [1, 3, 0]]

array([[10,  7,  1],
       [ 5,  9, 14],
       [ 7,  1,  5]])

In [17]:
# revrese the columns
a[:,::-1]

array([[ 7,  1, 10,  1],
       [ 9,  6,  5, 14],
       [ 1,  8,  7,  5]])

In [18]:
# with the salcing we can access rows and columns value
a[:,3][1]

9

In [19]:
a[:, 1][1]

5

# Assignments

#  Access the corner elements

In [20]:
a

array([[ 1, 10,  1,  7],
       [14,  5,  6,  9],
       [ 5,  7,  8,  1]])

In [21]:
a[::2, ::3]

array([[1, 7],
       [5, 1]])

#  change the corner elements to 0

In [22]:
a[::2, ::3] = 0

In [23]:
a

array([[ 0, 10,  1,  0],
       [14,  5,  6,  9],
       [ 0,  7,  8,  0]])

# i want to access 1,2 4 column

In [24]:
a[:, [0, 1, 3]]

array([[ 0, 10,  0],
       [14,  5,  9],
       [ 0,  7,  0]])

# i want to access 1,3,4 column

In [25]:
a[:, [0, 2, 3]]

array([[ 0,  1,  0],
       [14,  6,  9],
       [ 0,  8,  0]])

# without using eye and identity create 5x5 identity matrix 

In [26]:
d1 = np.zeros((5,5))
d1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# specified the array and value 
np.fill_diagonal(d1, 1)
d1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Conditional access to values

In [28]:
b = np.array([[12, 5, 6, 3], [10, 11, 9, 7],[6, 8, 13, 15]])

In [29]:
b

array([[12,  5,  6,  3],
       [10, 11,  9,  7],
       [ 6,  8, 13, 15]])

In [30]:
# check the value is greater than 10.
b > 10
# it will give boolean type output.

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True,  True]])

In [31]:
# how seen those value is greater than 10.
# arrayname[condition] then we can see the output.
b[b > 10]

array([12, 11, 13, 15])

In [32]:
b[b==10]

array([10])

In [33]:
b[b<12]

array([ 5,  6,  3, 10, 11,  9,  7,  6,  8])

In [34]:
# use only bitwise operator , logical operator get error
b[(b<10) & (b > 5)]

array([6, 9, 7, 6, 8])

## math operations on array

In [35]:
# its reflection, not inplace 
b + 10

array([[22, 15, 16, 13],
       [20, 21, 19, 17],
       [16, 18, 23, 25]])

In [36]:
# if we want change the in place go through the assingment operator.
b += 10

In [37]:
# 10 will be added 
b

array([[22, 15, 16, 13],
       [20, 21, 19, 17],
       [16, 18, 23, 25]])

In [38]:
# neglation
~b

array([[-23, -16, -17, -14],
       [-21, -22, -20, -18],
       [-17, -19, -24, -26]], dtype=int32)

In [39]:
b[b>6] + 10

array([32, 25, 26, 23, 30, 31, 29, 27, 26, 28, 33, 35])

In [40]:
b - 10

array([[12,  5,  6,  3],
       [10, 11,  9,  7],
       [ 6,  8, 13, 15]])

In [41]:
b * 2

array([[44, 30, 32, 26],
       [40, 42, 38, 34],
       [32, 36, 46, 50]])

In [42]:
# floor_divison
b // 2

array([[11,  7,  8,  6],
       [10, 10,  9,  8],
       [ 8,  9, 11, 12]], dtype=int32)

## Vector math on array

In [43]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
y = np.array([[7, 8, 9], [5, 3, 4]])
y

array([[7, 8, 9],
       [5, 3, 4]])

In [45]:
# reflection ,not inplace
x + y

array([[ 8, 10, 12],
       [ 9,  8, 10]])

In [46]:
# inplace
x += y

In [47]:
x

array([[ 8, 10, 12],
       [ 9,  8, 10]])

In [48]:
# array function
np.subtract(x, y)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.sum(x)

57

In [50]:
# addition
np.add(x, y)

array([[15, 18, 21],
       [14, 11, 14]])

In [51]:
np.floor_divide(x, y)

array([[1, 1, 1],
       [1, 2, 2]], dtype=int32)

# Aggregate operations
# min(), max(), std(), mean(),sum() 

In [52]:
# get minimum value in array
np.min(b)

13

In [53]:
# maximum value
np.max(b)

25

In [54]:
# standard deviation 
np.std(b)

3.418698582794336

In [55]:
# rowwise std, 1 means row
np.std(b, axis= 1)

array([3.35410197, 1.47901995, 3.64005494])

In [56]:
# columnwise std, 0 means colmuns
np.std(b, axis= 0)

array([2.49443826, 2.44948974, 2.86744176, 4.98887652])

In [57]:
# average of array
np.mean(b)

18.75

In [58]:
# sum of array
np.sum(b)

225

In [59]:
# Returns the median of the array elements.
np.median(b)

18.5

# var()
Compute the variance along the specified axis. Returns the variance of the array elements, a measure of the spread of a distribution.


In [60]:
# the variance along the specified axis.
np.var(b, axis= 1) # row

array([11.25  ,  2.1875, 13.25  ])

In [61]:
np.var(b, axis=0) # columns

array([ 6.22222222,  6.        ,  8.22222222, 24.88888889])

In [88]:
np.var([[1.2, 3.1],[3.2, 4.1]], axis= 0)

array([1.  , 0.25])

# corrcoef()

In [62]:
# Return Pearson product-moment correlation coefficients.
np.corrcoef(b)

array([[ 1.        ,  0.478755  , -0.77810715],
       [ 0.478755  ,  1.        , -0.8590724 ],
       [-0.77810715, -0.8590724 ,  1.        ]])

# power()

In [63]:
# First array elements raised to powers from second array
np.power(x,y)

array([[  2097152, 100000000, 864813056],
       [    59049,       512,     10000]], dtype=int32)

In [64]:
x

array([[ 8, 10, 12],
       [ 9,  8, 10]])

In [65]:
y

array([[7, 8, 9],
       [5, 3, 4]])

# array_equal()

In [66]:
# True if two arrays have the same shape and elements, False otherwise
np.array_equal(x, y)

False

In [67]:
np.array_equal([1, 2], [1, 2], [1, 2, 1, 2])

True

# array_equiv()

In [68]:
# Returns True if input arrays are shape consistent and all elements equal.
np.array_equiv(x,x)

True

In [69]:
np.array_equiv([1, 2], [1, 2])

True

In [70]:
np.array_equiv([1, 2], [[1, 2], [1, 2, 1, 2]])

c:\users\hp\python\python37\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


False

# sqrt()

In [71]:
# Return the non-negative square-root of an array, element-wise.
np.sqrt(b)

array([[4.69041576, 3.87298335, 4.        , 3.60555128],
       [4.47213595, 4.58257569, 4.35889894, 4.12310563],
       [4.        , 4.24264069, 4.79583152, 5.        ]])

# sin()

In [72]:
# Trigonometric sine, element-wise.
np.sin(b)

array([[-0.00885131,  0.65028784, -0.28790332,  0.42016704],
       [ 0.91294525,  0.83665564,  0.14987721, -0.96139749],
       [-0.28790332, -0.75098725, -0.8462204 , -0.13235175]])

In [73]:
np.sin(x)

array([[ 0.98935825, -0.54402111, -0.53657292],
       [ 0.41211849,  0.98935825, -0.54402111]])

# cos()

In [74]:
# Trigonometric sine, element-wise.
np.cos(b)

array([[-0.99996083, -0.75968791, -0.95765948,  0.90744678],
       [ 0.40808206, -0.54772926,  0.98870462, -0.27516334],
       [-0.95765948,  0.66031671, -0.53283302,  0.99120281]])

In [75]:
np.cos(y)

array([[ 0.75390225, -0.14550003, -0.91113026],
       [ 0.28366219, -0.9899925 , -0.65364362]])

#  log()

In [76]:
# Natural logarithm, element-wise.
np.log(b)

array([[3.09104245, 2.7080502 , 2.77258872, 2.56494936],
       [2.99573227, 3.04452244, 2.94443898, 2.83321334],
       [2.77258872, 2.89037176, 3.13549422, 3.21887582]])

# abs()

In [77]:
# Calculate the absolute value element-wise. 
np.abs(b)

array([[22, 15, 16, 13],
       [20, 21, 19, 17],
       [16, 18, 23, 25]])

In [78]:
np.abs(x)

array([[ 8, 10, 12],
       [ 9,  8, 10]])

In [79]:
np.abs([-1.2, 1.2])

array([1.2, 1.2])

In [80]:
np.abs([1, 1.0, -1, 1.2])

array([1. , 1. , 1. , 1.2])

# ceil()

In [81]:
# Return the ceiling of the input, element-wise.
np.ceil(b)

array([[22., 15., 16., 13.],
       [20., 21., 19., 17.],
       [16., 18., 23., 25.]])

In [82]:
np.ceil([-1.0, 0.0, 1.2, -1.2, 1.5, 0.2, -0.2, 1.7, 1.8, 2.0, 2.5,1.4])

array([-1.,  0.,  2., -1.,  2.,  1., -0.,  2.,  2.,  2.,  3.,  2.])

In [83]:
# Returns the closest integer greater than or equal to a given number. 
#Ceiling is often used as a rounding function. This is a single-value function.

# floor()

In [84]:
# Return the floor of the input, element-wise.
# if element is nigative, contains float value it will add one get nigative element.
# 
np.floor([1.0, 3.0, -3.0, 4.0, 5.0, 4.6, 6.0, -7.0])

array([ 1.,  3., -3.,  4.,  5.,  4.,  6., -7.])

# round()

In [85]:
# Round an array to the given number of decimals.
np.round(4.5)

4.0

In [86]:
# if .6 onwards return the decimal number.
np.round(4.6)

5.0