# Sort array

In [2]:
import numpy as np

In [3]:
a = np.array([[14, 10, 7], [4, 15, 21], [12, 54, 25], [45, 32, 22]])
a

array([[14, 10,  7],
       [ 4, 15, 21],
       [12, 54, 25],
       [45, 32, 22]])

In [4]:
# sort array usng sort function
# by default axis is -1 sort last axis(rowwise)
np.sort(a)

array([[ 7, 10, 14],
       [ 4, 15, 21],
       [12, 25, 54],
       [22, 32, 45]])

In [5]:
a

array([[14, 10,  7],
       [ 4, 15, 21],
       [12, 54, 25],
       [45, 32, 22]])

In [6]:
# rowwise sort
np.sort(a, axis=1)

array([[ 7, 10, 14],
       [ 4, 15, 21],
       [12, 25, 54],
       [22, 32, 45]])

In [7]:
# columnwise
np.sort(a, axis=0)

array([[ 4, 10,  7],
       [12, 15, 21],
       [14, 32, 22],
       [45, 54, 25]])

In [8]:
# kind parameter : optional
# kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}

In [9]:
a

array([[14, 10,  7],
       [ 4, 15, 21],
       [12, 54, 25],
       [45, 32, 22]])

In [10]:
np.sort(a, kind='quicksort')

array([[ 7, 10, 14],
       [ 4, 15, 21],
       [12, 25, 54],
       [22, 32, 45]])

In [11]:
np.sort(a,axis=0, kind='mergesort')

array([[ 4, 10,  7],
       [12, 15, 21],
       [14, 32, 22],
       [45, 54, 25]])

# How to reshape/manipulate arrays

In [12]:
a

array([[14, 10,  7],
       [ 4, 15, 21],
       [12, 54, 25],
       [45, 32, 22]])

In [13]:
# check the shape of array.
a.shape

(4, 3)

# reshape convert the 1D array to nD array

In [14]:
b = np.array(range(1, 13))
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
# 1D array to 2D array
# we need the shape(row,columns)
b.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
#reshape contain only one unknown diamension otherwise its give a value error
b.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
# 1D to 3D array
b.reshape(1, 4, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

# reshape convert the 2D array to nD array

In [18]:
a

array([[14, 10,  7],
       [ 4, 15, 21],
       [12, 54, 25],
       [45, 32, 22]])

In [19]:
# 2D to 3D array
a.reshape(1,3,-1)

array([[[14, 10,  7,  4],
        [15, 21, 12, 54],
        [25, 45, 32, 22]]])

In [20]:
# 2D to 1D
a.flatten()

array([14, 10,  7,  4, 15, 21, 12, 54, 25, 45, 32, 22])

# reshape convert the 3D array to nD array

In [21]:
s = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 12, 14]]])

In [22]:
s

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 12, 14]]])

In [23]:
# 3D to 2D
s.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 12, 14]])

In [24]:
# 3D to 1D 
s.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 14])

In [25]:
# we reshape the array but changes not inplace(in original array)

In [26]:
# inplace the shape of array.
s.resize(3,4)

In [27]:
# 3D array to 2D array.
# check "s" the shape will be changed in-place.
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 12, 14]])

In [28]:
# 2D to 1D array
s.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 14])

In [29]:
# #Return a copy of the array collapsed into one dimension.
s.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 14])

In [30]:
#shape is also used for in place changes in shape
s.shape = (12)

In [31]:
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 14])

# transpose array


In [32]:
a

array([[14, 10,  7],
       [ 4, 15, 21],
       [12, 54, 25],
       [45, 32, 22]])

In [33]:
#rows converted to column
a.T

array([[14,  4, 12, 45],
       [10, 15, 54, 32],
       [ 7, 21, 25, 22]])

In [34]:
np.transpose(a)

array([[14,  4, 12, 45],
       [10, 15, 54, 32],
       [ 7, 21, 25, 22]])

# Adding /Removing elements from array

In [35]:
a1 = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15],[16, 17, 18, 19]])

In [36]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
# Append values to the end of an array.
# rerurn the 1D array.
np.append(a1,[10,20,30,40,50])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 10, 20, 30, 40, 50])

In [38]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
# adding rows but reflected as columns will be added. row == 1
np.append(a1,[[10],[20],[30],[40],[50]], axis=1)

array([[ 0,  1,  2,  3, 10],
       [ 4,  5,  6,  7, 20],
       [ 8,  9, 10, 11, 30],
       [12, 13, 14, 15, 40],
       [16, 17, 18, 19, 50]])

In [40]:
#  adding the column but reflected as rows will be added # 0 means column 
np.append(a1, [[12, 14, 21, 45]], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [12, 14, 21, 45]])

# Insert()

In [41]:
#Insert values along the given axis before the given indices.
a

array([[14, 10,  7],
       [ 4, 15, 21],
       [12, 54, 25],
       [45, 32, 22]])

In [42]:
np.insert(a, 3, 144)

array([ 14,  10,   7, 144,   4,  15,  21,  12,  54,  25,  45,  32,  22])

In [43]:
##Assignment: Insert the values in between according to axis
#insert value 12 in column index 3
np.insert(a1,a1[0][3],12,axis=1) 

array([[ 0,  1,  2, 12,  3],
       [ 4,  5,  6, 12,  7],
       [ 8,  9, 10, 12, 11],
       [12, 13, 14, 12, 15],
       [16, 17, 18, 12, 19]])

# Delete: rows and columns

In [44]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
#Return a new array with sub-arrays along an axis deleted.
np.delete(a1, 2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

# Assignment: Delete the rows and columns in between according to axis¶

In [46]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
np.delete(a1,a1[0][1], axis= 1) # delete column index 1 

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19]])

In [49]:
np.delete(a1,a1[0][1], axis= 0) #delete row index 1 

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [50]:
#remove multiple elements(columns)
np.delete(a1,[0,1,-1],axis=1)

array([[ 2],
       [ 6],
       [10],
       [14],
       [18]])

In [51]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])