# creating array


In [1]:
import numpy as np
np.array([1,2,3])


array([1, 2, 3])

# 1-dimensional array

In [2]:
s= np.array([1,2,3,4,5,6])
s

array([1, 2, 3, 4, 5, 6])

In [3]:
#find size of array
s.size

6

In [4]:
# find the dimension of array
s.ndim

1

In [5]:
# find the shape of array 
s.shape

(6,)

In [6]:
# find the data type of array
s.dtype

dtype('int32')

In [7]:
# find the type of array
type(s)

numpy.ndarray

# Create 2-Dimension array

In [8]:
s2 = np.array([[1,2],[4,5]])
s2


array([[1, 2],
       [4, 5]])

In [9]:
# find the dimension of array
s2.ndim

2

In [10]:
# find the shape of array
s2.shape

(2, 2)

In [11]:
# find the data type of array
s2.dtype

dtype('int32')

In [12]:
#find the type of array
type(s2)

numpy.ndarray

# create 3-Dimension Array

In [13]:
s3 = np.array([[[1,2,3,],[4,5,6],[7,8,9]]])

s3  


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [14]:
s4 = np.array([[[1,2,3],[4,5,6,],[7,8,9]],[[9,8,7],[4,5,6],[3,2,1]]])
s4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]]])

In [15]:
# find the shape of s4 array
s4.shape

(2, 3, 3)

In [16]:
#find s4 data type  
s4.dtype 

dtype('int32')

In [17]:
# find dimension of array 
s3.shape

(1, 3, 3)

In [18]:
# find the size of array
s3.size

9

In [19]:
# find the data type of array
s3.dtype


dtype('int32')

In [20]:
#find the size of s4
s4.size

18

In [21]:
#find type of array
type(s3)

numpy.ndarray

# How to convert array to list

In [22]:
s3 = np.array([[[1,2,3,],[4,5,6],[7,8,9]]])
s3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
s3.tolist()


[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

# creating array using default function

In [24]:
# by default is float all zeros values
# np.zeros 1-D array
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [25]:
# np.zeros 2D array
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# np.zeros 3D array
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

# Create array with all one's

In [27]:
# np.ones 1-D array / its also by default float values
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
#np.ones 2-D array
np.ones((2,2)) # 2 rows and 2 columns

array([[1., 1.],
       [1., 1.]])

In [29]:
# np.ones 3-D array
np.ones((2,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# Identitiy matrix or diagonal are 1

In [30]:
#np.eye() 2-D array
a1 = np.eye(6)
a1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# arange() 

In [31]:
 np.arange(1,10) # end exclusive

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(1,50,2) # start, stop, step

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [33]:
# reverse the arange
np.arange(11,0,-1)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])