# np.linspace


In [7]:
import numpy as np
np.linspace(1,5,num=10,dtype="int")

array([1, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [9]:
x = np.linspace(1,4,10)
x

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [8]:
np.linspace(-7,7,15)


array([-7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,
        6.,  7.])

In [2]:
import numpy as np
np.info(full)

NameError: name 'full' is not defined

In [7]:
np.full((3,3),100,dtype="bool")

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])