In [1]:
import numpy as np

In [2]:
a = np.array(100)
a

array(100)

In [3]:
a.shape

()

In [4]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# indexing


In [5]:
# access the element but by default is access rows
b[0]

array([1, 2, 3, 4])

In [6]:
b[2]

array([ 9, 10, 11, 12])

In [7]:
b[1,0] = 6 # b[1][0] in-place change the value

In [8]:
b

array([[ 1,  2,  3,  4],
       [ 6,  6,  7,  8],
       [ 9, 10, 11, 12]])

# slicing

In [9]:
b[:]

array([[ 1,  2,  3,  4],
       [ 6,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
b[1:]

array([[ 6,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
b[::-1]# reverse the rows

array([[ 9, 10, 11, 12],
       [ 6,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [12]:
b

array([[ 1,  2,  3,  4],
       [ 6,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
b[1,0]=5

In [14]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
b[::2,0:-1]

array([[ 1,  2,  3],
       [ 9, 10, 11]])

# columns

In [16]:
b[:,:]# [rows,columns]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
b[:,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

# Access the corner elements

In [18]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
b[::2,::3]

array([[ 1,  4],
       [ 9, 12]])

# change the corner elements to 0

In [20]:
b[::2,::3]= 0

In [21]:
b

array([[ 0,  2,  3,  0],
       [ 5,  6,  7,  8],
       [ 0, 10, 11,  0]])

# access 6,7 10,21==>1,2,3,4

In [22]:
b[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [23]:
b[1:,1:3] = [1,2],[4,3]

In [24]:
b

array([[0, 2, 3, 0],
       [5, 1, 2, 8],
       [0, 4, 3, 0]])

# access 2,4 10,12 ==> 'A'

In [25]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype="str") 
c

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['9', '10', '11', '12']], dtype='<U2')

In [26]:
c[::2,1::2]="A"

In [27]:
c

array([['1', 'A', '3', 'A'],
       ['5', '6', '7', '8'],
       ['9', 'A', '11', 'A']], dtype='<U2')

# 

# i want to access 1,2 4 column

In [28]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
d[:,[0,1,3]]

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

# i want to access 1,3,4 column

In [30]:
d[:,[0,2,3]]

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

# # without using eye and identity create 5x5 identity matrix

In [31]:
d1 = np.zeros((5,5))
d1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.fill_diagonal(d1,1)

In [33]:
d1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
import numpy as np
d2 = np.full((5,5),0)
d2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [35]:
# another way

d2[0][0] = 1 
d2[1][1] = 1
d2[2][2] = 1
d2[3][3] = 1
d2[4][4] = 1

In [36]:
d2

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Conditional access to values

In [37]:
s = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
s[(s==3) | (s>6)] # Put only bitwise operator


array([ 3,  7,  8,  9, 10, 11, 12])

In [39]:
s[(s>3) & (s<10)]

array([4, 5, 6, 7, 8, 9])

In [40]:
s = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
s + 10 # refelection

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [42]:
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
 # if we want change the in place go through the assingment operator

In [44]:
s+= 10


In [45]:
s

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [46]:
s-=10

In [47]:
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
# sort the array
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
s.sort()

In [50]:
s+10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [51]:
s.sort()

In [52]:
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
f = np.array([[12,10],[14,9],[15,11]])
f

array([[12, 10],
       [14,  9],
       [15, 11]])

In [54]:
# sort rowise axis = 1 
np.sort(f,axis=1)

array([[10, 12],
       [ 9, 14],
       [11, 15]])

In [55]:
# sort columnwise axis ==> 0
np.sort(f,axis=0)

array([[12,  9],
       [14, 10],
       [15, 11]])

In [56]:
f.sort()

In [57]:
f

array([[10, 12],
       [ 9, 14],
       [11, 15]])

In [58]:
# Aggregate operations
# min(), max(), std(), mean(),sum()
f.max()

15

In [59]:
f.mean()

11.833333333333334

In [60]:
f.min()

9

In [61]:
f.std()

2.1147629234082532

In [62]:
f.sum()

71

In [63]:
f.argmax()

5

In [64]:
f.fill(1)

In [65]:
f

array([[1, 1],
       [1, 1],
       [1, 1]])

In [69]:
np.corrcoef(f)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])