In [1]:
import numpy as np

Types of array in numpy
1. 1-D array
2. 2-D array
3. 3-D array

# 1-D array

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
# check the dimension of array
a.ndim

1

In [4]:
# check the size of array
a.size

5

In [5]:
# using len() function
len(a)

5

In [6]:
# check the dtype of array
a.dtype

dtype('int32')

In [7]:
# check the type of array
type(a)

numpy.ndarray

# 2-D array

In [8]:
s = np.array([[1, 2, 3], [4, 5, 6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
s.ndim

2

In [10]:
s.size

6

In [11]:
# check the shape of array,get the form of tuple (row, columns)
s.shape

(2, 3)

In [12]:
s.dtype

dtype('int32')

# 3-D array

In [13]:
d = np.array([[[1, 2, 3], [4, 5, 6], [6, 4, 7]],[[14, 12, 25], [21, 23, 52], [45, 25, 21]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  4,  7]],

       [[14, 12, 25],
        [21, 23, 52],
        [45, 25, 21]]])

In [14]:
d.ndim

3

In [15]:
d.size

18

In [16]:
# get tuple (no block, row, column)
d.shape

(2, 3, 3)

# create array using default functions of numpy

In [25]:
# create array with all zero's
# 1-D array
s = np.zeros(5)
s

array([0., 0., 0., 0., 0.])

In [26]:
s.ndim

1

In [29]:
# 2-D array 
s1 = np.zeros((4,4))
s1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
s1.ndim

2

In [33]:
# 3-D array
s3 = np.zeros((2, 3, 3))
s3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
s3.ndim

3

In [41]:
# create array with all one's
a1 = np.ones((4, 4)) # 3-D array np.ones((1, 4, 4))
a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
# create identity matrix / array
# identity means diagonal elements are 1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# how to convert array to  list

In [46]:
b = np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
# tolist() convert array to list
b.tolist()

[[1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0]]

In [52]:
type(b.tolist())

list

In [53]:
# using list keyword
list(b)

[array([1., 1., 1., 1.]),
 array([1., 1., 1., 1.]),
 array([1., 1., 1., 1.]),
 array([1., 1., 1., 1.])]

#  arange() 

In [54]:
 # arange() is similar that python range function
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# reverse the arange(start, stop, step) start=> inclusive, step=> exclusive
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

# dtype of array and typecasting of array

In [68]:
# create array and  check the dtype of array
b1 = np.ones((5,5))
b1.dtype

dtype('float64')

In [71]:
# explicite Typecasting 
b1 = np.ones((5,5), dtype="int32")
b1.dtype

dtype('int32')

In [75]:
b2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [4, 7, 2, 3]])
b2.dtype

dtype('int32')

In [77]:
# i want to change the dtype of array 'int' to 'string'(object)
b2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [4, 7, 2, 3]], dtype= "object")
b2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 7, 2, 3]], dtype=object)

In [78]:
# bool dtype
np.array([1, 4, 5, 6, 4], dtype="bool")

array([ True,  True,  True,  True,  True])

In [79]:
# "", '' and  None are the false value
# if ' ' inside qoute space is present then it will the true, bcuse in str whitespace also object
np.array(['', ' ', '', ''], dtype = "bool")

array([False,  True, False, False])

In [81]:
np.array([None, None, None, None], dtype="bool")

array([False, False, False, False])

In [ ]:
# diffrent ways of creating of array:
1. np.array()
2. np.arange()
3. np.eye()
4. np.ones()
5. np.zero's()
6. np.linspace()

# np.linspace

In [ ]:
# Linspace get the array of linear space
# by default generate 50 values
# endpoint = True then stop also inclusive
# we want sinwave or coswave that time we need linear spacing
#retstep get spacing value

In [83]:
# 1 to 10 between 50 number with linear spacing
np.linspace(1, 10) 

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [100]:
# how to check the spacing
# retstep is 1.0
np.linspace(1, 50, retstep= True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]),
 1.0)

In [88]:
# -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6
np.linspace(-6, 6, num=13)

array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])

# np.full()

In [115]:
#Return a new array of given shape and type, filled with `fill_value`
#np.full(shape, fill_value, dtype=None, order='C')
# if we want to shape as input then pass the value in () 
np.full((4,4), 10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [113]:
# we can change the dtype
np.full((4,4), 10, dtype="f2")

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]], dtype=float16)

In [116]:
# create 3D array
np.full((2, 4, 4), 12)

array([[[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]])

# Random()

In [126]:
# #Random values in a given shape.
# random will create random float values, it will need shape or one values/positional arguments
np.random.random((2, 4, 4))

array([[[0.57567451, 0.08625078, 0.85828311, 0.56392266],
        [0.49280269, 0.91674133, 0.44875322, 0.92334475],
        [0.45389397, 0.79137723, 0.30123964, 0.92317488],
        [0.3969171 , 0.99741611, 0.76104367, 0.68970476]],

       [[0.83153418, 0.80072792, 0.66719021, 0.61597689],
        [0.99862484, 0.3282204 , 0.96864335, 0.90686761],
        [0.28513514, 0.19933938, 0.15228986, 0.11872349],
        [0.00473552, 0.36471776, 0.78431214, 0.654832  ]]])

In [121]:
# its need only shape
# Random values in a given shape.
np.random.rand(4,4)

array([[0.93400804, 0.40153338, 0.13185493, 0.17206732],
       [0.44565528, 0.87644697, 0.95189854, 0.66802199],
       [0.82451869, 0.5153763 , 0.14779473, 0.3141534 ],
       [0.85110549, 0.20520953, 0.97147208, 0.42523344]])

In [123]:
# we can performs here as arithmatic operations
np.random.rand(4,4)+10

array([[10.30541467, 10.60202275, 10.99072005, 10.64733169],
       [10.92126607, 10.39477844, 10.19341757, 10.12021573],
       [10.47367321, 10.64861492, 10.57225619, 10.39930643],
       [10.59144177, 10.04413136, 10.90552666, 10.5561096 ]])

In [124]:
# multiplication
np.random.rand(4,4)*100

array([[91.60736681, 36.49379396, 67.59880701, 33.2518316 ],
       [93.46901011,  3.41046278, 49.5864495 , 99.25505128],
       [65.23046881, 37.8237267 , 58.58057029, 46.22845077],
       [90.5178324 , 41.63665177, 46.6317698 , 47.56452753]])

In [127]:
# subtraction
np.random.rand(4,4)-12

array([[-11.5466675 , -11.15317846, -11.09475232, -11.25750794],
       [-11.69077283, -11.52405141, -11.4205598 , -11.66242484],
       [-11.61759799, -11.16199133, -11.71847405, -11.02836897],
       [-11.94832698, -11.86717124, -11.03803712, -11.6341095 ]])

In [130]:
# devision or flor division
np.random.rand(4,4)/2

array([[0.20182827, 0.34366192, 0.49368291, 0.46215664],
       [0.40292834, 0.29247117, 0.43146211, 0.11270724],
       [0.42889338, 0.28764663, 0.39501565, 0.25526664],
       [0.07752386, 0.26065089, 0.15545377, 0.27629454]])

# Random.random.randint()

In [ ]:
# randint(low, high=None, size=None, dtype=int)
# Return random integers from `low` (inclusive) to `high` (exclusive).
# return the random intergers number.

In [137]:
np.random.randint(1, 11, size= 10)

array([ 7,  3,  1,  5,  1, 10,  4,  8, 10,  4], dtype=int64)

In [138]:
# randint is datatype is integer we can't perform type casting here, see the below example
np.random.randint(1, 11, size= 10, dtype="float16")

TypeError: Unsupported dtype dtype('float16') for randint

In [139]:
# only change int64 to int32
np.random.randint(1, 11, size= 10, dtype="int32")

array([ 7, 10,  7,  9,  9,  7,  7,  3,  1,  4])

In [140]:
# only change int32 to int16
np.random.randint(1, 11, size= 10, dtype="int16")

array([3, 9, 1, 5, 5, 9, 5, 1, 8, 5], dtype=int16)

In [147]:
# we see arithmatic operation in random
# they get only refelction of output
# how to inplace of the changes
x = np.random.randint(1, 11, 12)
x

array([9, 1, 1, 3, 1, 7, 4, 5, 9, 1, 9, 1])

In [148]:
# here they dont get the ouput bcause, the changes will be inplace(result store in x)
x += 10

In [149]:
x

array([19, 11, 11, 13, 11, 17, 14, 15, 19, 11, 19, 11])

#  I want to create 4x4 array which will contain all True values

In [150]:
np.ones((4,4), dtype="bool")

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# I want to create 4x4 array which will contain all False values

In [151]:
np.zeros((4,4), dtype="bool")

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# I want to create 5x5 array in which Diagonal values should be True & non diagonal values should be False

In [156]:
np.eye(5, dtype="bool")

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [157]:
np.identity(5, dtype="bool")

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])