# Numpy

In [32]:
#array==> ndarray
#array supports indexing==> +ve & -ve indexing
# slicing
import numpy
numpy.array(object,dtype=None)

array(<class 'object'>, dtype=object)

## Creating arrays using numpy

In [33]:
import numpy as np

In [34]:
np

<module 'numpy' from 'c:\\users\\hp\\python\\python37\\lib\\site-packages\\numpy\\__init__.py'>

In [35]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [36]:
np.array([[1,2],[4,4]])

array([[1, 2],
       [4, 4]])

## np.array(object,dtype)

In [37]:
a = np.array([1,2,3,4,5])
a.dtype

dtype('int32')

In [38]:
a

array([1, 2, 3, 4, 5])

In [39]:
# ExpliciteTypecasting
a = np.array([1,2,3,4,5],dtype='float')
a.dtype

dtype('float64')

In [40]:
a

array([1., 2., 3., 4., 5.])

In [41]:
#i want float32 instead float64
a = np.array([1,2,3,4,5],dtype='float32')
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [42]:
a = np.array([1,2,3,4,5],dtype='float16')
a

array([1., 2., 3., 4., 5.], dtype=float16)

In [43]:
a = np.array([1,2,3,4,5],dtype='bool')
a

array([ True,  True,  True,  True,  True])

In [44]:
np.array(['','','',''],dtype='bool')

array([False, False, False, False])

In [45]:
np.array([None, None, None],dtype='bool')

array([False, False, False])

In [46]:
#different way
np.array()
np.arange()
np.eye()
np.ones()
np.zeros()

TypeError: array() missing required argument 'object' (pos 1)

### np.linspace

In [47]:
"""
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
"""
np.linspace(2,20)

array([ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
        3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
        5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
        7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
        9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653,
       11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
       13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
       14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
       16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
       18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ])

In [48]:
np.linspace(2,6,num=10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [49]:
np.linspace(-6,6,8)

array([-6.        , -4.28571429, -2.57142857, -0.85714286,  0.85714286,
        2.57142857,  4.28571429,  6.        ])

In [50]:
# -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6
np.linspace(-6,6,13)

array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])

In [51]:
np.linspace(2,6,num=10,retstep=True)

(array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
        4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]),
 0.4444444444444444)

In [52]:
np.linspace(-6,6,num=13,retstep=True)

(array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.]), 1.0)

In [53]:
np.linspace(1,6,num=13,retstep=True)

(array([1.        , 1.41666667, 1.83333333, 2.25      , 2.66666667,
        3.08333333, 3.5       , 3.91666667, 4.33333333, 4.75      ,
        5.16666667, 5.58333333, 6.        ]),
 0.4166666666666667)

## np.full()

In [54]:
#Return a new array of given shape and type, filled with `fill_value`
#np.full(shape, fill_value, dtype=None, order='C')
#shape=()
np.full((4,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [ ]:
np.full((4,4),100,dtype=np.float32)#f8 f==float32
#dtype: 'float','f8',np.float32

## random()

In [ ]:
#Random values in a given shape.
np.random.rand(5)

In [55]:
np.random.random((2,6,3)) # random will create random float values, it will need shape or one values/positional arguments
                         

array([[[0.7362485 , 0.2244627 , 0.30733399],
        [0.79220851, 0.68320151, 0.00656092],
        [0.83358106, 0.79936096, 0.39525779],
        [0.50024728, 0.47417107, 0.64809892],
        [0.30664556, 0.18386758, 0.30351475],
        [0.94398678, 0.91639266, 0.59182507]],

       [[0.32211522, 0.14514595, 0.27645536],
        [0.24301336, 0.71740395, 0.7402638 ],
        [0.28274883, 0.70034122, 0.11084084],
        [0.20453053, 0.47594026, 0.1759114 ],
        [0.03674722, 0.86071951, 0.67527681],
        [0.51933508, 0.40397358, 0.82296599]]])

In [56]:
d = np.random.rand(3,3)
d

array([[0.39080183, 0.4818264 , 0.37685104],
       [0.56964771, 0.18968241, 0.19685886],
       [0.75413941, 0.24273991, 0.04823719]])

In [57]:
d.dtype

dtype('float64')

In [58]:
d.size

9

In [59]:
d.shape

(3, 3)

In [60]:
d.ndim

2

In [61]:
x = np.random.rand(4,4)
x

array([[0.96381941, 0.60521652, 0.94421835, 0.78788727],
       [0.63712102, 0.72495676, 0.1346288 , 0.32636483],
       [0.6321164 , 0.84418132, 0.54272881, 0.99683704],
       [0.54930489, 0.13666437, 0.06603365, 0.10889819]])

In [62]:
x*=100
x

array([[96.38194069, 60.5216524 , 94.42183472, 78.78872668],
       [63.71210231, 72.49567579, 13.46287956, 32.63648278],
       [63.21163964, 84.41813227, 54.27288078, 99.68370392],
       [54.93048916, 13.66643679,  6.60336507, 10.88981923]])

In [ ]:
#randint(low, high=None, size=None, dtype=int)

#Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(3,size=12)

In [ ]:
np.random.randint(2,12,size=20,dtype='int8')

In [ ]:
a = np.random.randint(2,6,10,dtype='int')
a

In [ ]:
a.dtype

In [63]:
#age = 18-35
np.random.randint(18,36,22)

array([25, 30, 34, 33, 20, 21, 26, 28, 27, 30, 29, 26, 20, 28, 32, 27, 34,
       28, 18, 30, 21, 33])

In [ ]:
a

In [ ]:
x/= -10000
x

In [ ]:
id(x)

In [ ]:
# create array y same as that of x
y = x

In [ ]:
y

In [ ]:
id(y)

In [ ]:
z = np.copy(x)
z

In [ ]:
id(z)

In [ ]:
# I want to create 4x4 array which will contain all True values
# I want to create array which will contain all False values
# I want to create 5x5 array in which Diagonal values should be True & non diagonal values should be False



In [ ]:
np.random.rand(5,5)